name: Weather Bot(From Joker)

on:
  # push:
  schedule:
    - cron: '30 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./run.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: 吴小妍的天气预报
          body: file://result.html
          to: yihchu694800687@163.com,18641646723@163.com
          # to: yihchu694800687@163.com
          from: 憨憨 
          content_type: text/html
